name: Build cockpit-files .deb (Bookworm)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-deb:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm
      options: --user root

    steps:
    - name: Checkout this workflow repo (required)
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          curl \
          git \
          gettext \
          make \
          devscripts \
          build-essential \
          fakeroot \
          ca-certificates

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        check-latest: true

    - name: Clone cockpit-files repo
      run: |
        git clone https://github.com/cockpit-project/cockpit-files.git /tmp/cockpit-files

    - name: Build Debian package
      working-directory: /tmp/cockpit-files
      run: |
        make packaging/debian/changelog
        mv packaging/debian debian
        debuild -us -uc

    - name: Upload .deb artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cockpit-deb-package
        path: |
          /tmp/*.deb
          /tmp/*.build
          /tmp/*.changes
